export const HOMESCREEN = 'HomeScreen'
export const LOGINSCREEN = 'LoginScreen'
export const SIGNUPSCREEN = 'SignUpScreen'
export const ORDER_TAB = 'Order Now'
export const USER_PROFILE_TAB = 'Profile'
export const PRO_TAB = 'Get Pro'
export const DINE_OUT_TAB = 'Dine Out'
